// Chain names and IDs.
export const TESTNET_SEPOLIA_CHAIN_IDs = {
  ARBITRUM_SEPOLIA: 421614,
  BASE_SEPOLIA: 84532,
  BLAST_SEPOLIA: 168587773,
  BOB_SEPOLIA: 808813,
  HYPEREVM_TESTNET: 998,
  INK_SEPOLIA: 763373,
  TATARA: 129399,
  LENS_SEPOLIA: 37111,
  LISK_SEPOLIA: 4202,
  MODE_SEPOLIA: 919,
  MONAD_TESTNET: 10143,
  OPTIMISM_SEPOLIA: 11155420,
  PLASMA_TESTNET: 9746,
  POLYGON_AMOY: 80002,
  SCROLL_SEPOLIA: 534351,
  SEPOLIA: 11155111,
  UNICHAIN_SEPOLIA: 1301,
  ZK_SYNC_SEPOLIA: 300,
};

export const TESTNET_CHAIN_IDs = {
  ...TESTNET_SEPOLIA_CHAIN_IDs,
  SOLANA_DEVNET: 133268194659241,
} as const;

export const MAINNET_CHAIN_IDs = {
  ALEPH_ZERO: 41455,
  ARBITRUM: 42161,
  BASE: 8453,
  BLAST: 81457,
  BOB: 60808,
  BSC: 56,
  BOBA: 288,
  HYPEREVM: 999,
  HYPERCORE: 1337, // Arbitrary chain ID for HyperCore but consistent with other APIs
  INK: 57073,
  LENS: 232,
  LIGHTER: 2337,
  LINEA: 59144,
  LISK: 1135,
  MAINNET: 1,
  MEGAETH: 4326,
  MODE: 34443,
  MONAD: 143,
  OPTIMISM: 10,
  PLASMA: 9745,
  POLYGON: 137,
  REDSTONE: 690,
  SCROLL: 534352,
  SONEIUM: 1868,
  SUPERSEED: 5330,
  TEMPO: 4217,
  UNICHAIN: 130,
  WORLD_CHAIN: 480,
  ZK_SYNC: 324,
  ZORA: 7777777,
  SOLANA: 34268394551451,
};

export const CHAIN_IDs = {
  ...MAINNET_CHAIN_IDs,
  ...TESTNET_CHAIN_IDs,
};

export enum ChainFamily {
  NONE,
  OP_STACK,
  ORBIT, // Future: Might need to distinguish between ORBIT_L2 and ORBIT_L3...
  ZK_STACK,
  SVM,
}

// Source https://docs.layerzero.network/v2/developers/evm/technical-reference/deployed-contracts
export const PRODUCTION_OFT_EIDs = {
  ARBITRUM: 30110,
  BASE: 30184,
  BLAST: 30243,
  BSC: 30102,
  HYPEREVM: 30367,
  INK: 30339,
  MAINNET: 30101,
  MONAD: 30390,
  MEGAETH: 30398,
  OPTIMISM: 30111,
  PLASMA: 30383,
  POLYGON: 30109,
  SONEIUM: 30340,
  TEMPO: 30410,
  UNICHAIN: 30320,
  WORLD_CHAIN: 30319,
  SOLANA: 30168,
};

// Source https://docs.layerzero.network/v2/developers/evm/technical-reference/deployed-contracts
export const TESTNET_OFT_EIDs = {
  ARBITRUM_SEPOLIA: 40231,
  BASE_SEPOLIA: 40245,
  OPTIMISM_SEPOLIA: 40232,
  HYPEREVM_TESTNET: 40362,
  MONAD_TESTNET: 40204,
  POLYGON_AMOY: 40267,
  SEPOLIA: 40161,
  UNICHAIN_SEPOLIA: 40333,
  SOLANA_DEVNET: 40168,
};

// Collection of Hyperlane domain ids that are different from CHAIN_IDs.
// Source https://github.com/hyperlane-xyz/hyperlane-registry
export const HYPERLANE_DOMAIN_ID_OVERRIDES = {
  SOLANA: 1399811149,
  SOLANA_DEVNET: 1399811151,
};

interface PublicNetwork {
  name: string;
  family: ChainFamily;
  nativeToken: string;
  publicRPC: string; // RPC provider of last resort.
  blockExplorer: string;
  cctpDomain: number;
  oftEid: number;
  hypDomainId: number; // Hyperlane domain id
}

export const CCTP_NO_DOMAIN = -1;
export const OFT_NO_EID = -1;
export const HYPERLANE_NO_DOMAIN_ID = -1;

const { NONE, OP_STACK, ORBIT, SVM, ZK_STACK } = ChainFamily;
export const PRODUCTION_NETWORKS: { [chainId: number]: PublicNetwork } = {
  [CHAIN_IDs.ALEPH_ZERO]: {
    name: "Aleph Zero",
    family: ORBIT,
    nativeToken: "AZERO",
    publicRPC: "https://rpc.alephzero.raas.gelato.cloud",
    blockExplorer: "https://evm-explorer.alephzero.org",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.ARBITRUM]: {
    name: "Arbitrum One",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://arb1.arbitrum.io/rpc",
    blockExplorer: "https://arbiscan.io",
    cctpDomain: 3,
    oftEid: PRODUCTION_OFT_EIDs.ARBITRUM,
    hypDomainId: MAINNET_CHAIN_IDs.ARBITRUM,
  },
  [CHAIN_IDs.BASE]: {
    name: "Base",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://mainnet.base.org",
    blockExplorer: "https://basescan.org",
    cctpDomain: 6,
    oftEid: PRODUCTION_OFT_EIDs.BASE,
    hypDomainId: MAINNET_CHAIN_IDs.BASE,
  },
  [CHAIN_IDs.BLAST]: {
    name: "Blast",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://rpc.blast.io",
    blockExplorer: "https://blastscan.io",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: PRODUCTION_OFT_EIDs.BLAST,
    hypDomainId: MAINNET_CHAIN_IDs.BLAST,
  },
  [CHAIN_IDs.BSC]: {
    name: "BNB Smart Chain",
    family: NONE,
    nativeToken: "BNB",
    publicRPC: "https://bsc-dataseed1.binance.org",
    blockExplorer: "https://bscscan.com",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: PRODUCTION_OFT_EIDs.BSC,
    hypDomainId: MAINNET_CHAIN_IDs.BSC,
  },
  [CHAIN_IDs.BOBA]: {
    name: "Boba",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://mainnet.boba.network",
    blockExplorer: "https://blockexplorer.boba.network",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.HYPEREVM]: {
    name: "HyperEVM",
    family: NONE,
    nativeToken: "HYPE",
    publicRPC: "https://rpc.hyperliquid.xyz/evm",
    blockExplorer: "https://hyperevmscan.io/",
    cctpDomain: 19,
    oftEid: PRODUCTION_OFT_EIDs.HYPEREVM,
    hypDomainId: CHAIN_IDs.HYPEREVM,
  },
  [CHAIN_IDs.HYPERCORE]: {
    name: "HyperCore",
    family: NONE,
    nativeToken: "HYPE",
    publicRPC: "https://api.hyperliquid.xyz",
    blockExplorer: "https://app.hyperliquid.xyz/explorer",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.UNICHAIN]: {
    name: "Unichain",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://mainnet.unichain.org/",
    blockExplorer: "https://uniscan.xyz",
    cctpDomain: 10,
    oftEid: PRODUCTION_OFT_EIDs.UNICHAIN,
    hypDomainId: MAINNET_CHAIN_IDs.UNICHAIN,
  },
  [CHAIN_IDs.INK]: {
    name: "Ink",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://rpc-gel.inkonchain.com",
    blockExplorer: "https://explorer.inkonchain.com",
    cctpDomain: 21,
    oftEid: PRODUCTION_OFT_EIDs.INK,
    hypDomainId: MAINNET_CHAIN_IDs.INK,
  },
  [CHAIN_IDs.TATARA]: {
    name: "Tatara",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "",
    blockExplorer: "",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.LENS]: {
    name: "Lens",
    family: ZK_STACK,
    nativeToken: "WGHO",
    publicRPC: "https://api.lens.matterhosted.dev",
    blockExplorer: "https://explorer.lens.xyz",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.LIGHTER]: {
    name: "Lighter",
    family: NONE,
    nativeToken: "LIT",
    publicRPC: "https://mainnet.zklighter.elliot.ai",
    blockExplorer: "https://app.lighter.xyz/explorer",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.LINEA]: {
    name: "Linea",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://rpc.linea.build",
    blockExplorer: "https://lineascan.build",
    cctpDomain: 11,
    oftEid: OFT_NO_EID,
    hypDomainId: MAINNET_CHAIN_IDs.LINEA,
  },
  [CHAIN_IDs.LISK]: {
    name: "Lisk",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://rpc.api.lisk.com",
    blockExplorer: "https://blockscout.lisk.com",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.MAINNET]: {
    name: "Mainnet",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://eth.llamarpc.com",
    blockExplorer: "https://etherscan.io",
    cctpDomain: 0,
    oftEid: PRODUCTION_OFT_EIDs.MAINNET,
    hypDomainId: MAINNET_CHAIN_IDs.MAINNET,
  },
  [CHAIN_IDs.MEGAETH]: {
    name: "MegaETH",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://mainnet.megaeth.com/rpc",
    blockExplorer: "https://megaeth.blockscout.com",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: PRODUCTION_OFT_EIDs.MEGAETH,
    hypDomainId: MAINNET_CHAIN_IDs.MEGAETH,
  },
  [CHAIN_IDs.MODE]: {
    name: "Mode",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://mainnet.mode.network",
    blockExplorer: "https://explorer.mode.network",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: MAINNET_CHAIN_IDs.MODE,
  },
  [CHAIN_IDs.MONAD]: {
    name: "Monad",
    family: NONE,
    nativeToken: "MON",
    publicRPC: "https://rpc-mainnet.monadinfra.com",
    blockExplorer: "https://monadvision.com",
    cctpDomain: 15,
    oftEid: PRODUCTION_OFT_EIDs.MONAD,
    hypDomainId: MAINNET_CHAIN_IDs.MONAD,
  },
  [CHAIN_IDs.OPTIMISM]: {
    name: "Optimism",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://mainnet.optimism.io",
    blockExplorer: "https://optimistic.etherscan.io",
    cctpDomain: 2,
    oftEid: PRODUCTION_OFT_EIDs.OPTIMISM,
    hypDomainId: MAINNET_CHAIN_IDs.OPTIMISM,
  },
  [CHAIN_IDs.PLASMA]: {
    name: "Plasma",
    family: NONE,
    nativeToken: "XPL",
    publicRPC: "https://rpc.plasma.to",
    blockExplorer: "https://plasmascan.to",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: PRODUCTION_OFT_EIDs.PLASMA,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.POLYGON]: {
    name: "Polygon",
    family: NONE,
    nativeToken: "POL",
    publicRPC: "https://polygon-rpc.com",
    blockExplorer: "https://polygonscan.com",
    cctpDomain: 7,
    oftEid: PRODUCTION_OFT_EIDs.POLYGON,
    hypDomainId: MAINNET_CHAIN_IDs.POLYGON,
  },
  [CHAIN_IDs.REDSTONE]: {
    name: "Redstone",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://rpc.redstonechain.com",
    blockExplorer: "https://explorer.redstone.xyz",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: MAINNET_CHAIN_IDs.REDSTONE,
  },
  [CHAIN_IDs.SCROLL]: {
    name: "Scroll",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://rpc.scroll.io",
    blockExplorer: "https://scrollscan.com",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.SOLANA]: {
    name: "Solana",
    family: SVM,
    nativeToken: "SOL",
    publicRPC: "https://api.mainnet-beta.solana.com",
    blockExplorer: "https://solscan.io",
    cctpDomain: 5,
    oftEid: PRODUCTION_OFT_EIDs.SOLANA,
    hypDomainId: HYPERLANE_DOMAIN_ID_OVERRIDES.SOLANA,
  },
  [CHAIN_IDs.SONEIUM]: {
    name: "Soneium",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://rpc.soneium.org",
    blockExplorer: "https://soneium.blockscout.com",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: PRODUCTION_OFT_EIDs.SONEIUM,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.SUPERSEED]: {
    name: "Superseed",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://mainnet.superseed.xyz",
    blockExplorer: "", // @todo: To be added later
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.TEMPO]: {
    name: "Tempo",
    family: NONE,
    nativeToken: "pathUSD", // While there is no native token on Tempo, pathUSD is the default fee token.
    publicRPC: "https://rpc.tempo.xyz",
    blockExplorer: "https://explore.mainnet.tempo.xyz",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: PRODUCTION_OFT_EIDs.TEMPO,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.WORLD_CHAIN]: {
    name: "World Chain",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://worldchain-mainnet.g.alchemy.com/public",
    blockExplorer: "https://worldchain-mainnet-explorer.alchemy.com",
    cctpDomain: 14,
    oftEid: PRODUCTION_OFT_EIDs.WORLD_CHAIN,
    hypDomainId: MAINNET_CHAIN_IDs.WORLD_CHAIN,
  },
  [CHAIN_IDs.ZK_SYNC]: {
    name: "zkSync",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://mainnet.era.zksync.io",
    blockExplorer: "https://explorer.zksync.io",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: MAINNET_CHAIN_IDs.ZK_SYNC,
  },
  [CHAIN_IDs.ZORA]: {
    name: "Zora",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://rpc.zora.energy",
    blockExplorer: "https://zorascan.xyz",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
};

export const TEST_NETWORKS: { [chainId: number]: PublicNetwork } = {
  [CHAIN_IDs.ARBITRUM_SEPOLIA]: {
    name: "Arbitrum Sepolia",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://sepolia-rollup.arbitrum.io/rpc",
    blockExplorer: "https://sepolia.arbiscan.io",
    cctpDomain: 3,
    oftEid: TESTNET_OFT_EIDs.ARBITRUM_SEPOLIA,
    hypDomainId: TESTNET_CHAIN_IDs.ARBITRUM_SEPOLIA,
  },
  [CHAIN_IDs.BASE_SEPOLIA]: {
    name: "Base Sepolia",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://sepolia.base.org",
    blockExplorer: "https://sepolia.basescan.org",
    cctpDomain: 6,
    oftEid: TESTNET_OFT_EIDs.BASE_SEPOLIA,
    hypDomainId: TESTNET_CHAIN_IDs.BASE_SEPOLIA,
  },
  [CHAIN_IDs.BLAST_SEPOLIA]: {
    name: "Blast Sepolia",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://sepolia.blast.io",
    blockExplorer: "https://sepolia.blastscan.io",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: TESTNET_CHAIN_IDs.BLAST_SEPOLIA,
  },
  [CHAIN_IDs.BOB_SEPOLIA]: {
    name: "BOB Sepolia",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://bob-sepolia.rpc.gobob.xyz",
    blockExplorer: "https://bob-sepolia.explorer.gobob.xyz",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.HYPEREVM_TESTNET]: {
    name: "HyperEVM Testnet",
    family: NONE,
    nativeToken: "HYPE",
    publicRPC: "https://rpc.hyperliquid-testnet.xyz/evm",
    blockExplorer: "https://testnet.purrsec.com/",
    cctpDomain: 19,
    oftEid: TESTNET_OFT_EIDs.HYPEREVM_TESTNET,
    hypDomainId: TESTNET_CHAIN_IDs.HYPEREVM_TESTNET,
  },
  [CHAIN_IDs.LENS_SEPOLIA]: {
    name: "Lens Sepolia",
    family: ZK_STACK,
    nativeToken: "GRASS",
    publicRPC: "https://rpc.testnet.lens.dev",
    blockExplorer: "https://block-explorer.testnet.lens.dev",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.LISK_SEPOLIA]: {
    name: "Lisk Sepolia",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://rpc.sepolia-api.lisk.com",
    blockExplorer: "https://sepolia-blockscout.lisk.com",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.MODE_SEPOLIA]: {
    name: "Mode Sepolia",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://sepolia.mode.network",
    blockExplorer: "https://sepolia.explorer.mode.network",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: TESTNET_CHAIN_IDs.MODE_SEPOLIA,
  },
  [CHAIN_IDs.MONAD_TESTNET]: {
    name: "Monad Testnet",
    family: NONE,
    nativeToken: "MON",
    publicRPC: "https://testnet-rpc.monad.xyz",
    blockExplorer: "https://testnet.monvision.io",
    cctpDomain: 15,
    oftEid: TESTNET_OFT_EIDs.MONAD_TESTNET,
    hypDomainId: TESTNET_CHAIN_IDs.MONAD_TESTNET,
  },
  [CHAIN_IDs.OPTIMISM_SEPOLIA]: {
    name: "Optimism Sepolia",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://sepolia.optimism.io",
    blockExplorer: "https://sepolia-optimism.etherscan.io",
    cctpDomain: 2,
    oftEid: TESTNET_OFT_EIDs.OPTIMISM_SEPOLIA,
    hypDomainId: TESTNET_CHAIN_IDs.OPTIMISM_SEPOLIA,
  },
  [CHAIN_IDs.PLASMA_TESTNET]: {
    name: "Plasma Testnet",
    family: NONE,
    nativeToken: "XPL",
    publicRPC: "https://testnet-rpc.plasma.to/",
    blockExplorer: "https://testnet.plasmascan.to/",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.POLYGON_AMOY]: {
    name: "Polygon Amoy",
    family: NONE,
    nativeToken: "POL",
    publicRPC: "https://rpc-amoy.polygon.technology",
    blockExplorer: "https://amoy.polygonscan.com",
    cctpDomain: 7,
    oftEid: TESTNET_OFT_EIDs.POLYGON_AMOY,
    hypDomainId: TESTNET_CHAIN_IDs.POLYGON_AMOY,
  },
  [CHAIN_IDs.SCROLL_SEPOLIA]: {
    name: "Scroll Sepolia",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://sepolia-rpc.scroll.io",
    blockExplorer: "https://sepolia.scrollscan.com",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: HYPERLANE_NO_DOMAIN_ID,
  },
  [CHAIN_IDs.SEPOLIA]: {
    name: "Sepolia",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://sepolia.drpc.org",
    blockExplorer: "https://sepolia.etherscan.io",
    cctpDomain: 0,
    oftEid: TESTNET_OFT_EIDs.SEPOLIA,
    hypDomainId: TESTNET_CHAIN_IDs.SEPOLIA,
  },
  [CHAIN_IDs.SOLANA_DEVNET]: {
    name: "Solana Devnet",
    family: SVM,
    nativeToken: "SOL",
    publicRPC: "https://api.devnet.solana.com",
    blockExplorer: "https://explorer.solana.com/?cluster=devnet",
    cctpDomain: 5,
    oftEid: TESTNET_OFT_EIDs.SOLANA_DEVNET,
    hypDomainId: HYPERLANE_DOMAIN_ID_OVERRIDES.SOLANA_DEVNET,
  },
  [CHAIN_IDs.UNICHAIN_SEPOLIA]: {
    name: "Unichain Sepolia",
    family: OP_STACK,
    nativeToken: "ETH",
    publicRPC: "https://sepolia.unichain.org",
    blockExplorer: "https://sepolia.uniscan.xyz",
    cctpDomain: 10,
    oftEid: TESTNET_OFT_EIDs.UNICHAIN_SEPOLIA,
    hypDomainId: TESTNET_CHAIN_IDs.UNICHAIN_SEPOLIA,
  },
  [CHAIN_IDs.ZK_SYNC_SEPOLIA]: {
    name: "zkSync Sepolia",
    family: NONE,
    nativeToken: "ETH",
    publicRPC: "https://sepolia.era.zksync.dev",
    blockExplorer: "https://sepolia-era.zksync.network",
    cctpDomain: CCTP_NO_DOMAIN,
    oftEid: OFT_NO_EID,
    hypDomainId: TESTNET_CHAIN_IDs.ZK_SYNC_SEPOLIA,
  },
};

export const PUBLIC_NETWORKS = {
  ...PRODUCTION_NETWORKS,
  ...TEST_NETWORKS,
};
